### ISSUE TITLE
Stage mitxonline users_user

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#334]
- [ ] what are the raw fields
- [ ] write up a plan for each field, including modifications to the field name, data types, data to omit, etc. 
- [ ] open a PR the implements the plan for `users_user`

**Comment by Ferdi** [comment]
```
id
username
email
created_on_utc
updated_on_utc
is_active
last_login_utc
```

We are dropping `is_staff` , `is_supperuser` since they are simply used by django [internally](https://github.com/mitodl/hq/issues/266#issuecomment-1258253936) to specify who is [allowed](https://stackoverflow.com/a/20470185) to view certain pages. 

I'm not sure we need to prefix fields with `user_` .   I think the table/model name will serve as a namespace.

**Comment by abeglova** [comment]
I don't think the `updated_on` is useful - it's just a field that django automatically updates. Should be just after last_login most of the time, whenever the script to update the last_login actually runs

**Comment by abeglova** [comment]
We can just filter out users where is_active=False. That flag is used to delete accounts.

**Comment by Ferdi** [comment]
> We can just filter out users where is_active=False. That flag is used to delete accounts.

I think we should keep them around.  The might be needed in lookups (e.g customer service) , they might have enrollments in the past etc.

**Comment by abeglova** [comment]
Ok I think the plan should be to create a separate table for users where is_active = False in the staging layer so those users aren't accidentally included
