### ISSUE TITLE
Stage mitxonline users_changeemailrequest

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#339]
- [ ] what are the raw fields
- [ ] write up a plan for each field, including modifications to the field name, data types, data to omit, etc. 
- [ ] open a PR the implements the plan for `users_changeemailrequest`

**Comment by abeglova** [comment]
The columns are 
id
code - verification code for when the user clicks an email link confirming they want to change the email
user_id
confirmed - whether confirmed the email change by going through the verification link
new_email
created_on
expires_on
updated_on

**Comment by abeglova** [comment]
This table is used to keep track of email change requests because a user needs to confirm the change through a link sent to their email and there is a celery job that needs to monitor the status of the request.

Tracking email changes is useful because we will join on email to combine to other data sources. Unfortunately this table doesn't have a "current_email" column which makes it less useful. I think for now we don't import this but we should consider adding a code change to add the old email to these records

**Comment by abeglova** [comment]
Correction - there isn't actually a celery task - just a wait until the user responds to the email varification

**Comment by rhysyngsun** [comment]
Talked to Ferdi about this so I understood what we're doing more - @abeglova I agree with you on not bringing in this table for now. 

What this table is currently providing is a singly linked list where we can infer the values of all the nodes except the first one. A doubly linked list to be able to provide that first element is what we really need to make this data useful and we'd need the `current_email` column you mentioned to make that possible.

Definitely a good improvement to make in the applications, but not impactful to the work right now.
