### ISSUE TITLE
Stage mitxonline `courses_course`

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#381]
Stage mitxonline `courses_course`

- [ ]  list the fields for `courses_course`
- [ ] plan for each field, including modifications to the field name, data types, data to omit, etc.
- [ ] open a PR that implements it

**Comment by rachellougee** [comment]
This table is staged as it-is from the source
```
    select
        id
        , live
        , title
        , program_id
        , readable_id as course_readable_id
        , position_in_program
        , created_on
        , updated_on
    from source
```

But I think we should fix the created_on and updated_on to convert to ISO8601 format as we did for the user's table
to_iso8601(from_iso8601_timestamp(created_on)) 
and add it to the staging models yml file

**Comment by Ferdi** [comment]
* `live` is not clear
* `program_id` and `position_in_program` : I can guess what they are for , but would be good to confirm  /cc @rhysyngsun

**Comment by rhysyngsun** [comment]
In terms of mitx online both `program_id` and `position_in_program` will very likely be going away and replaced by a lookup through the program requirements because these fields don't support courses being in multiple programs and the requirements represent those courses being under a particular program. We could certainly project the new data structures into this data model but I'd advise avoiding bringing those fields over unless having a course record per unique `program_id` is desirable (I'd guess it's not).

The field `live` is used to distinguish courses that will show up anywhere in user-facing UIs and backend logic. This functionality lets us stage the courses prior to them being rolled out officially so that we can get all the appropriate data in place. Generally the only place `live=False` courses will be accessible is in django-admin.

**Comment by rachellougee** [comment]
@Ferdi Per Nathan's comment, do you agree we should omit `program_id` and `position_in_program` to staging for now?

**Comment by abeglova** [comment]
Does it make sense to keep program_id and position_in_program for now until the new lookup table is implemented? @rhysyngsun how soon do you expect that work to happen. There isn't currently another way to tell what courses are in a program

**Comment by rachellougee** [comment]
We are keeping program_id and position_in_program for now until Nathan's PR for program requirement is merged and used on production
