### ISSUE TITLE
Update open-edx pipeline to match SQL file output for Simeon

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-data-platform#610]
# User Story
- As a member of IRx I want the Open edX data exports from Open Learning to conform to the interface that is offered by the output of the [edx-analytics-exporter](https://github.com/openedx/edx-analytics-exporter/blob/master/exporter/tasks.py#L186)

# Description/Context
We have an existing pipeline definition that exports data from our Open edX environments on a nightly schedule. This pipeline definition was written to conform to the interface that was expected by a legacy data consumer. We now need to support a data consumer that is using https://github.com/MIT-IR/simeon/ to process our outputs. This necessitates some refactoring of our pipeline and updates to the file names/file contents that are generated.

# Acceptance Criteria
- [ ] The file names of the data that is exported matches what is generated from the edx-analytics-exporter
- [x] The contents of the SQL tables match what is generated by the edx-analytics-exporter
- [ ] The file outputs are placed in per-course directories
- [x] All of the SQL queries run in the edx-analytics-exporter are included in the output results of our pipeline

# Notes and Resources
- edx-analytics-exporter task definitions - https://github.com/openedx/edx-analytics-exporter/blob/master/exporter/tasks.py#L430
  - This has all of the SQL queries that are needed for the final output and the file names to use

**Comment by pdpinch** [comment]
Is this issue still in progress?

**Comment by blarghmatey** [comment]
In order to align this workflow with our overall data platform we want to generate all of the SQL table definitions via dbt and consolidate them into a grouping of models to be consumed by MIT IRx. Once those tables are managed through dbt we will then generate the CSV file exports as Airbyte connections from Trino -> S3.

**Comment by pdpinch** [comment]
I believe this is in-process, so I'm moving it.

**Comment by quazi-h** [comment]
The new dbt models have been tested and validated and merged to production. The next step would be to make sure the data is being exported to a format matching the edX data that IRx currently gets. That is a .zip file that is delivered via S3 with one directory per course, with each directory containing just the data for that course, with the filenames being identical course-to-course. It would also require some transformations to address discrepancies between our data and edX data.

One specific issue is that our profile data uses different categories for some variables (ex. level of education). Another example is course structure, which uses an XML file of course exports from openedX but a course-structure JSON file on the edX side that is generated by a script that is not part of the standard openedX library.  Some transformation is necessary to in order to have our output match the same output of the edX data. In order to work with our existing output, irX has had to add patches to resolve these differences (see below). If we change our output without changing those things, irX would need to put additional work in to make the data usable.

We could implement the transformations on our side but the main hurdle for us is that it is nontrivial for us to change our output to conform to the one directory per course structure that Jon would need. For now, we have merged the [new dbt models](https://github.com/mitodl/ol-data-platform/pull/965) to production and have those available for when and if this becomes a priority for irX.

[user profile data](https://github.mit.edu/IR/adhoc_projects/blob/master/charley_for_obscured/join_users_profiles.py)
[internal course structure data](https://github.mit.edu/IR/simeon-internal/blob/11b35e9e164820ac91f84fdf7231c9fc08b764d7/simeon_internal/splitting/utilities.py#L501) vs [edX course structure data](https://github.mit.edu/IR/simeon/blob/ab01ac163585741354de58574acad30ced848b38/simeon/report/utilities.py#L679)
