### ISSUE TITLE
Add student and other roles to course_roles for open edx

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#627]
# Description/Context

We are working on getting learners' activities for our open edx data from IRx BigQuery, two of the user activities fields are all null due to lacking roles data in [role_query.csv.](https://github.com/mitodl/ol-data-platform/blob/main/src/ol_orchestrate/ops/open_edx.py#L328) Currently, we populate this file with data in `student_courseaccessrole`, but it only includes staff and instructors. In the Simeon script, it requires more [roles](https://github.com/MIT-IR/simeon/blob/main/simeon/report/utilities.py#L1168-L1183) than what we provide.  We should be able to get the following roles by joining `django_comment_client_role_users` and `django_comment_client_role` tables in our open edx database, but please confirm if that's the case. Thank. 
```
Administrator
Community
Community TA
Moderator
Student
```

# Acceptance Criteria
- [ ] Add remaining roles to `role_query.csv` for all our Open edX export. 
      Edit: It could be a new file if it's easier, as long as it includes the `user_id`, `course_id`, `name` and `role` columns same as role_query.csv

**Comment by rachellougee** [comment]
This blocks https://github.mit.edu/IR/simeon-internal/issues/29, which then blocks https://github.com/mitodl/ol-data-platform/issues/626. If we could work on it, that'd be great

**Comment by rachellougee** [comment]
@quazi-h That should be fine to provide all we have, that additional role will just not be used. Thank you for working on it.

**Comment by quazi-h** [comment]
Hi @rachellougee I put up a draft PR with the changes needed to get the student roles. I agree that it makes sense to create a separate file since the query is completely different so my changes should create a new file - role_users.csv. I just need to test the changes and get a review before I can merge it and close this issue.

I was discussing these changes with @blarghmatey and he noted that he's not totally sure if the _comment_client_ tables equate to the same concept of a role that is being used elsewhere. Because a user can have a given role for the course, as well as having a given role for the discussion forums for the course but we're not sure which concept those "comment_client" tables map to.

**Comment by quazi-h** [comment]
This is complete, changes from https://github.com/mitodl/ol-data-platform/pull/629 have been merged.
The new role_users file has the same columns as the role_query file.
<img width="1129" alt="Screenshot 2023-03-24 at 9 25 54 AM" src="https://user-images.githubusercontent.com/59845076/227566778-3369a950-1217-43b0-a2b9-60102e9e5a39.png">
